### ISSUE TITLE
Почему бы в пользователя сразу не положить его роль?

### ISSUE THREAD

**Issue by coursar** [MajorPayne36/web-app#10]
https://github.com/MajorPayne36/web-app/blob/f17a5270afa0010b65053ed6a4401e7a9dd9b9bb/src/main/java/org/example/app/service/CardService.java#L29

**Comment by MajorPayne36** [comment]
Чтобы роль бралось из БД, так как, по идее, роль может поменяться, поэтому пусть берет свежие данные
